Linlin
XintangZ/ecommerce_bookstore pull request #4
Opened 2024-08-23 00:11 UTC by Carolyn1204

2024-08-23 00:26 UTC, XintangZ commented on server/src/routes/order.route.ts
1. all order routs should use jwt auth middleware (the user should login to perform these actions)
2. suggested endpoint design:

	// Create a new order
	router.post('/orders', authenticateJWT, createOrder);

	// Get all orders
	router.get('/orders', authenticateJWT, getAllOrders);

	// Get a specific order by ID
	router.get('/orders/:id', authenticateJWT, getOrder);

	// Update an order by ID
	router.put('/orders/:id', authenticateJWT, updateOrder);

2024-08-23 00:34 UTC, XintangZ commented on server/src/schema/order.schema.ts
> +    userId: z.string().min(1, { message: 'Invalid user ID format' }),
userId can be obtained from decoded jwt

2024-08-23 00:34 UTC, XintangZ commented on server/src/controllers/order.controller.ts
> +    try {
get userId from decoded jwt

2024-08-23 00:44 UTC, XintangZ commented on server/src/controllers/order.controller.ts
> +    const { page = 1, limit = 10 } = req.query;
1. check if the decoded user is admin. yes->2. no->3.
2. check if the request comes with a query param (/orders?userId=blablabla), yes->4. no->5.
3. return all orders matching the decoded userId (the current logged in user)
4. return all orders matching the provided userId
5. return all orders in the db

2024-08-23 00:53 UTC, XintangZ requested changes

2024-08-23 00:53 UTC, XintangZ commented on server/src/controllers/order.controller.ts
> +        }
1. after the order is found
2. check if the decoded user is admin. yes->2. no->3.
3. return the found order 
4. check if the found order's userId matches the decoded userId, yes->5. no->6.
5. return the found order
6. return 403 forbidden

2024-08-23 00:53 UTC, XintangZ commented on server/src/controllers/order.controller.ts
> +    try {
get userId from decoded jwt

2024-08-23 00:53 UTC, XintangZ commented on server/src/controllers/order.controller.ts
> +
1. check if the decoded user is admin. yes->2. no->3.
2. check if the request comes with a query param (/orders?userId=blablabla), yes->4. no->5.
3. return all orders matching the decoded userId (the current logged in user)
4. return all orders matching the provided userId
5. return all orders in the db

2024-08-23 00:53 UTC, XintangZ commented on server/src/controllers/order.controller.ts
> +        const updatedOrder = await Order.findByIdAndUpdate(
1. find the order
2. check if the status from the request is 'cancel'. yes->3. no->4.
3. update the order, return
4. check if the decoded user is admin. yes->3. no->5.
5. return 403 forbidden

2024-08-23 00:53 UTC, XintangZ commented on server/src/routes/order.route.ts
1. all order routs should use jwt auth middleware (the user should login to perform these actions)
2. suggested endpoint design:

	// Create a new order
	router.post('/orders', authenticateJWT, createOrder);

	// Get all orders
	router.get('/orders', authenticateJWT, getAllOrders);

	// Get a specific order by ID
	router.get('/orders/:id', authenticateJWT, getOrder);

	// Update an order by ID
	router.put('/orders/:id', authenticateJWT, updateOrder);

2024-08-23 00:53 UTC, XintangZ commented on server/src/schema/order.schema.ts
> +    userId: z.string().min(1, { message: 'Invalid user ID format' }),
userId can be obtained from decoded jwt

2024-08-23 22:56 UTC, XintangZ approved these changes

2024-08-23 23:16 UTC, XintangZ approved these changes

2024-08-24 08:53 UTC, aqizzz approved these changes
LGTM

2024-08-24 08:53 UTC, merged